# Generated by Django 3.2 on 2021-12-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='Sifat', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='Sylhet', max_length=50),
        ),
    ]
